In [1]:
import pandas as pd
import numpy as np

C:\Users\G-A-M\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [71]:
df=pd.read_csv("Titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [72]:
drop_cols=["PassengerId","Ticket","Name"]

In [73]:

# from config.config import drop_cols

def drop_column(df :pd.DataFrame ,cols:list[str])-> pd.DataFrame:
    """ 
        drop specific colmnus from dataframe
    
    """ 
    
    
    return df.drop(columns=cols)

In [74]:
df=drop_column(df, drop_cols)

In [75]:
# df.drop(["PassengerId","Ticket","Name"],axis=1, inplace=True)

In [76]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

## Ckeck Data Type

In [77]:
dtypes=df.dtypes

n_unique=df.nunique()
n_unique

Survived      2
Pclass        3
Sex           2
Age          88
SibSp         7
Parch         7
Fare        248
Cabin       147
Embarked      3
dtype: int64

In [78]:
pd.DataFrame({"Dtypes: ": dtypes,"Num_unique: ":n_unique}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Dtypes:,int64,int64,str,float64,int64,int64,float64,str,str
Num_unique:,2,3,2,88,7,7,248,147,3

In [79]:
def get_check_dtype(df:pd.DataFrame)-> pd.DataFrame:
    return pd.DataFrame({"Dtypes: ": df.dtypes,"Num_unique: ":df.nunique()}).T

In [80]:
from ps import get_check_dtype
get_check_dtype(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Dtypes:,int64,int64,str,float64,int64,int64,float64,str,str
Num_unique:,2,3,2,88,7,7,248,147,3

In [81]:
cols=["Sex","Pclass","Survived","SibSp","Parch","Embarked"]
df[cols]=df[cols].astype("category")

pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,str,category

In [82]:
def change_cols(df: pd.DataFrame):
    cols = ["Sex", "Pclass", "Survived", "SibSp", "Parch", "Embarked"]
    
    df[cols] = df[cols].astype("category")
    
    return df

In [83]:
change_cols(df)

    Survived Pclass     Sex   Age SibSp Parch     Fare Cabin Embarked
0          0      3    male  22.0     1     0   7.2500   NaN        S
1          1      1  female  38.0     1     0  71.2833   C85        C
2          1      3  female  26.0     0     0   7.9250   NaN        S
3          1      1  female  35.0     1     0  53.1000  C123        S
4          0      3    male  35.0     0     0   8.0500   NaN        S
..       ...    ...     ...   ...   ...   ...      ...   ...      ...
886        0      2    male  27.0     0     0  13.0000   NaN        S
887        1      1  female  19.0     0     0  30.0000   B42        S
888        0      3  female   NaN     1     2  23.4500   NaN        S
889        1      1    male  26.0     0     0  30.0000  C148        C
890        0      3    male  32.0     0     0   7.7500   NaN        Q

[891 rows x 9 columns]

In [84]:
null_values=df.isnull().sum()
null_values

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [85]:

type(null_values)

pandas.Series

In [86]:
ratio_val = null_values / df.shape[0]

pd.DataFrame({
    "nulls_sum": null_values,
    "Ratio": ratio_val
}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
nulls_sum,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.000000,2.000000
Ratio,0.0,0.0,0.0,0.198653,0.0,0.0,0.0,0.771044,0.002245

In [87]:
df =df.dropna(subset=["Embarked"])

In [88]:
df=df.drop("Cabin",axis=1)

In [89]:
df

    Survived Pclass     Sex   Age SibSp Parch     Fare Embarked
0          0      3    male  22.0     1     0   7.2500        S
1          1      1  female  38.0     1     0  71.2833        C
2          1      3  female  26.0     0     0   7.9250        S
3          1      1  female  35.0     1     0  53.1000        S
4          0      3    male  35.0     0     0   8.0500        S
..       ...    ...     ...   ...   ...   ...      ...      ...
886        0      2    male  27.0     0     0  13.0000        S
887        1      1  female  19.0     0     0  30.0000        S
888        0      3  female   NaN     1     2  23.4500        S
889        1      1    male  26.0     0     0  30.0000        C
890        0      3    male  32.0     0     0   7.7500        Q

[889 rows x 8 columns]

In [101]:
mean = df["Age"].mean()
print("Mean:", mean)

median = df["Age"].median()
print("Median:", median)

print("=" * 20)

df["Age"] = df["Age"].fillna(median)

Mean: 29.64209269662921
Median: 28.0
====================

In [102]:
null_values = df.isnull().sum()

ratio_val = null_values / df.shape[0]

pd.DataFrame({
    "nulls_sum": null_values,
    "Ratio": ratio_val
}).T

           Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
nulls_sum       0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
Ratio           0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

In [103]:
df.describe()

              Age        Fare
count  889.000000  889.000000
mean    29.315152   32.096681
std     12.984932   49.697504
min      0.420000    0.000000
25%     22.000000    7.895800
50%     28.000000   14.454200
75%     35.000000   31.000000
max     80.000000  512.329200

In [104]:
nums_cols=df.select_dtypes("number").columns
nums_cols

Index(['Age', 'Fare'], dtype='str')

In [105]:
nums_cols=['Age', 'Fare']