In [2]:
!pip intall pasndas

In [1]:

import pandas as pd

C:\Users\G-A-M\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
s =pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
s=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
data=[
    [1,444,"abc"],
    [2,555,"def"],
    [3,666,"ghi"],
    [4,777,"xyz"]
    ]


df=pd.DataFrame(data, columns=["idx","std_id","std_depart"])
df

   idx  std_id std_depart
0    1     444        abc
1    2     555        def
2    3     666        ghi
3    4     777        xyz

In [21]:
import pandas as pd

data = {
    "idx": range(1, 101),
    "std_id": range(444, 544),
    "std_depart": [
        "abc", "def", "ghi", "xyz"
    ] * 25
}

df = pd.DataFrame(data)

print(df)

    idx  std_id std_depart
0     1     444        abc
1     2     445        def
2     3     446        ghi
3     4     447        xyz
4     5     448        abc
..  ...     ...        ...
95   96     539        xyz
96   97     540        abc
97   98     541        def
98   99     542        ghi
99  100     543        xyz

[100 rows x 3 columns]

In [22]:
display(df)

    idx  std_id std_depart
0     1     444        abc
1     2     445        def
2     3     446        ghi
3     4     447        xyz
4     5     448        abc
..  ...     ...        ...
95   96     539        xyz
96   97     540        abc
97   98     541        def
98   99     542        ghi
99  100     543        xyz

[100 rows x 3 columns]

In [23]:
columns = ["idx-1", "std_id1", "dep"]


df.columns = columns

display(df)

    idx-1  std_id1  dep
0       1      444  abc
1       2      445  def
2       3      446  ghi
3       4      447  xyz
4       5      448  abc
..    ...      ...  ...
95     96      539  xyz
96     97      540  abc
97     98      541  def
98     99      542  ghi
99    100      543  xyz

[100 rows x 3 columns]

In [18]:
df.dtypes

idx-1      int64
std_id1    int64
dep          str
dtype: object

In [24]:
df.columns

Index(['idx-1', 'std_id1', 'dep'], dtype='str')

In [28]:
df["idx-1"].dtype

dtype('int64')

In [31]:
df["idx-1"]=df["idx-1"].astype("category")
df.dtypes

idx-1      category
std_id1       int64
dep             str
dtype: object

In [32]:
cols=["std_id1","dep"]
df[cols]=df[cols].astype("category")
df.dtypes

idx-1      category
std_id1    category
dep        category
dtype: object

In [33]:
import pandas as pd

data = {
    "idx": range(1, 101),
    "std_id": range(444, 544),
    "std_depart": [
        "abc", "def", "ghi", "xyz"
    ] * 25
}

df = pd.DataFrame(data)

print(df)

    idx  std_id std_depart
0     1     444        abc
1     2     445        def
2     3     446        ghi
3     4     447        xyz
4     5     448        abc
..  ...     ...        ...
95   96     539        xyz
96   97     540        abc
97   98     541        def
98   99     542        ghi
99  100     543        xyz

[100 rows x 3 columns]

In [ ]:

df.dtypes

idx           int64
std_id        int64
std_depart      str
dtype: object

In [35]:
df.head()

   idx  std_id std_depart
0    1     444        abc
1    2     445        def
2    3     446        ghi
3    4     447        xyz
4    5     448        abc

In [36]:
df.tail()

    idx  std_id std_depart
95   96     539        xyz
96   97     540        abc
97   98     541        def
98   99     542        ghi
99  100     543        xyz

In [38]:
df.describe()

              idx      std_id
count  100.000000  100.000000
mean    50.500000  493.500000
std     29.011492   29.011492
min      1.000000  444.000000
25%     25.750000  468.750000
50%     50.500000  493.500000
75%     75.250000  518.250000
max    100.000000  543.000000

In [39]:
df["std_depart"]=df["std_depart"].astype("category")
df.dtypes

idx              int64
std_id           int64
std_depart    category
dtype: object

In [40]:
df["std_depart"].describe()

count     100
unique      4
top       abc
freq       25
Name: std_depart, dtype: object

In [41]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [48]:
df["std_depart"].unique()
df["std_id"].idxmin

<bound method Series.idxmin of 0     444
1     445
2     446
3     447
4     448
     ...
95    539
96    540
97    541
98    542
99    543
Name: std_id, Length: 100, dtype: int64>

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   idx         100 non-null    int64
 1   std_id      100 non-null    int64
 2   std_depart  100 non-null    category
dtypes: category(1), int64(2)
memory usage: 2.0 KB

In [52]:
df.isnull()

      idx  std_id  std_depart
0   False   False       False
1   False   False       False
2   False   False       False
3   False   False       False
4   False   False       False
..    ...     ...         ...
95  False   False       False
96  False   False       False
97  False   False       False
98  False   False       False
99  False   False       False

[100 rows x 3 columns]

In [53]:
df["std_depart"].value_counts()

std_depart
abc    25
def    25
ghi    25
xyz    25
Name: count, dtype: int64

In [56]:
x=df.values
type(x)

numpy.ndarray

In [61]:
df=df.replace(444, 200, inplace=True)
df

    idx  std_id std_depart
0     1     200        abc
1     2     445        def
2     3     446        ghi
3     4     447        xyz
4     5     448        abc
..  ...     ...        ...
95   96     539        xyz
96   97     540        abc
97   98     541        def
98   99     542        ghi
99  100     543        xyz

[100 rows x 3 columns]

In [63]:
df.sort_values

<bound method DataFrame.sort_values of     idx  std_id std_depart
0     1     200        abc
1     2     445        def
2     3     446        ghi
3     4     447        xyz
4     5     448        abc
..  ...     ...        ...
95   96     539        xyz
96   97     540        abc
97   98     541        def
98   99     542        ghi
99  100     543        xyz

[100 rows x 3 columns]>

In [68]:
x=df.iloc[0:10,0:2]
x

   idx  std_id
0    1     200
1    2     445
2    3     446
3    4     447
4    5     448
5    6     449
6    7     450
7    8     451
8    9     452
9   10     453

In [ ]:
df.dropna()

    idx  std_id std_depart
0     1     200        abc
1     2     445        def
2     3     446        ghi
3     4     447        xyz
4     5     448        abc
..  ...     ...        ...
95   96     539        xyz
96   97     540        abc
97   98     541        def
98   99     542        ghi
99  100     543        xyz

[100 rows x 3 columns]

: